---
title: "data exploration"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) ## Data Manipulaion
library(dplyr)
library(arsenal)
library(ggplot2)
library(patchwork)
library(HH)
```

```{r}
lawsuit = 
read_csv("data/Lawsuit.csv") %>% 
   janitor::clean_names() %>% 
  mutate(dept = factor(dept,levels = c(1:6),
                       labels =
                    c("Biochemistry","Physiology","Genetics",
                      "Pediatrics","Medicine","Surgery")),
         gender = factor(gender,levels = c(0:1),
                       labels =
                    c("Female","Male")),
         clin = factor(clin,levels = c(0:1),
                       labels =
                    c("Research","Clinical")),
         cert = factor(cert,levels = c(0:1),
                       labels =
                    c("Not certified","Broad certified")),
         rank = factor(rank,levels = c(1:3),
                       labels =
                    c("Assistant","Associate","Full professor")))

```

Summarize all variables by gender
```{r}
 sum_data  <-  arsenal::tableby( gender ~ dept + clin + cert + 
                                 prate + exper + rank + sal94	+
                                 sal95, 
                                data  = lawsuit,
                                test  = FALSE, 
                                total = FALSE,
                                numeric.stats =
                                  c("meansd","medianq1q3","range"))
summ = summary(sum_data,text = TRUE)
summ %>% 
  knitr::kable(format = "html")
```

Distributions
```{r}
gg_94 = 
lawsuit %>% 
 ggplot(aes(sal94,..density..))+
 geom_histogram()+
 geom_line(stat = 'density',size = 1)+
    labs(x = "sal94")

gg_95 = 
lawsuit %>% 
 ggplot(aes(sal95,..density..))+
 geom_histogram()+
 geom_line(stat = 'density',size = 1)+
    labs(x = "sal95")

gg_94 + gg_95
```

Possible transformation

```{r}
lawsuit_log = 
lawsuit %>% 
  mutate(log_sal94 = log(sal94),
         log_sal95 = log(sal95)) %>% 
  dplyr::select(-sal94,-sal95)

gg_94 = 
lawsuit_log %>% 
 ggplot(aes(log_sal94,..density..))+
 geom_histogram()+
 geom_line(stat = 'density',size = 1)+
    labs(x = "log_sal94")

gg_95 = 
lawsuit_log %>% 
 ggplot(aes(log_sal95,..density..))+
 geom_histogram()+
 geom_line(stat = 'density',size = 1)+
    labs(x = "log_sal95")

gg_94 + gg_95
  
```

# Confounders for 94

```{r}
lawsuit_log_94 =
lawsuit_log %>% 
    dplyr::select(-log_sal95,-id)


con = lm(log_sal94 ~ gender, data = lawsuit_log_94) %>% summary()
con_1 = lm(log_sal94 ~ gender + dept, data = lawsuit_log_94) %>% summary()
con_2 = lm(log_sal94 ~ gender + clin, data = lawsuit_log_94) %>% summary()
con_3 = lm(log_sal94 ~ gender + cert, data = lawsuit_log_94) %>% summary()
con_4 = lm(log_sal94 ~ gender + prate, data = lawsuit_log_94) %>% summary()
con_5 = lm(log_sal94 ~ gender + exper, data = lawsuit_log_94) %>% summary()
con_6 = lm(log_sal94 ~ gender + rank, data = lawsuit_log_94) %>% summary()

con_tab_94 = tibble("variables" = c("gender", "gender + dept", "gender + clin", "gender + cert", "gender + prate", "gender + exper", "gender + rank"), "coef" = c(con$coefficients[2],con_1$coefficients[2],con_2$coefficients[2],con_3$coefficients[2],con_4$coefficients[2],con_5$coefficients[2],con_6$coefficients[2]))

con_tab_94 %>% mutate(
  diff = abs((coef[1]-coef)/coef[1]),
  confounder = ifelse(diff>=0.1, "Y", "N")
)

con_tab_94
(0.2251-0.2024)/0.2251

# Except for rank, all covariates are confounders
```


# 94 salary
```{r}

mul.fit <- lm(log_sal94 ~ .,lawsuit_log_94)
summary(mul.fit)

# let gender be a stratified factor

mul.fit_all_gender <- lm(log_sal94 ~ . + 
              gender*rank + gender*clin + gender*cert +
              gender*prate + gender*rank + gender*dept
              ,lawsuit_log_94)
summary(mul.fit_all_gender)


# only gender*rank is significant
mul.fit_fixed_gender <- lm(log_sal94 ~ . + gender*rank, lawsuit_log_94)
summary(mul.fit_fixed_gender)

# remove non-significant variable: prate
# test model with and without prate
mul.fit_no_prate <- update(mul.fit_fixed_gender, . ~ . -prate)
summary(mul.fit_no_prate)

# ANONA test model with all interaction terms and model with only gender*rank 
anova(mul.fit_fixed_gender,mul.fit_all_gender)
# Choose small model

# ANOVA
# P>0.05
# choose small model wothout prate
anova(mul.fit_no_prate,mul.fit_fixed_gender)

# Final stratified model
# should we remove prate????????
mul.fit_no_prate <- update(mul.fit_fixed_gender, . ~ . -prate)
summary(mul.fit_no_prate)
```

stepwise 
```{r}
#step(mul.fit_no_prate,direction='backward')
#
#mul.fit_fixed_gender <- lm(log_sal94 ~ . + gender*rank, lawsuit_log_94)
#summary(mul.fit_fixed_gender)
#
#step(mul.fit_fixed_gender,direction='backward')
#
#
## whole medel stepwise
#model_all = lm(log_sal94 ~ . + 
#              gender*rank + gender*clin + gender*cert +
#              gender*prate + gender*rank + gender*dept
#              ,lawsuit_log_94)
#step(model_all,direction='backward')

```


```{r}
# ANOVA with and without prate
model1 = lm(formula = log_sal94 ~ dept + clin + cert + exper + 
    rank + gender:rank + gender, data = lawsuit_log_94)

model2 = lm(formula = log_sal94 ~ dept + clin + cert + exper + 
    rank , data = lawsuit_log_94)

anova(model2, model1)

```

# Stratified model by rank
```{r}
lawsuit_log_94_prof = 
lawsuit_log_94 %>% 
  filter(rank == "Full professor")

lawsuit_log_94_asso = 
lawsuit_log_94 %>% 
  filter(rank == "Associate")

lawsuit_log_94_assi = 
lawsuit_log_94 %>% 
  filter(rank == "Assistant")

model_prof = lm(formula = log_sal94 ~ dept + clin + cert + exper + gender, data = lawsuit_log_94_prof)

model_asso = lm(formula = log_sal94 ~ dept + clin + cert + exper + gender, data = lawsuit_log_94_asso)

model_assi = lm(formula = log_sal94 ~ dept + clin + cert + exper + gender, data = lawsuit_log_94_assi)

summary(model_prof)
summary(model_asso)
summary(model_assi)
```

# model diagnosis
# 94
```{r}
# prate has multicollinearity
vif(model_prof)
vif(model_asso)
vif(model_assi)

```

heteroscedasticity, normality
```{r}
# outlier: 4th,51th,65th
par(mfrow=c(2,2))
plot(model_prof)

# outlier: 47th, 15th
par(mfrow=c(2,2))
plot(model_asso)

# influencial point: 68th
par(mfrow=c(2,2))
plot(model_assi)
```

remove 68th in model_assi
```{r}

# remove 68th, gender is not significant
model_assi = lm(formula = log_sal94 ~ dept + clin + cert + exper + gender, data = lawsuit_log_94_assi[-68,])
summary(model_assi)

par(mfrow=c(2,2))
plot(model_assi)

```


# Confounder 95

```{r}
lawsuit_log_95 =
lawsuit_log %>% 
    dplyr::select(-log_sal94,-id)

con = lm(log_sal95 ~ gender, data = lawsuit_log_95) %>% summary()
con_1 = lm(log_sal95 ~ gender + dept, data = lawsuit_log_95) %>% summary()
con_2 = lm(log_sal95 ~ gender + clin, data = lawsuit_log_95) %>% summary()
con_3 = lm(log_sal95 ~ gender + cert, data = lawsuit_log_95) %>% summary()
con_4 = lm(log_sal95 ~ gender + prate, data = lawsuit_log_95) %>% summary()
con_5 = lm(log_sal95 ~ gender + exper, data = lawsuit_log_95) %>% summary()
con_6 = lm(log_sal95 ~ gender + rank, data = lawsuit_log_95) %>% summary()

con_tab_95 = tibble("variables" = c("gender", "gender + dept", "gender + clin", "gender + cert", "gender + prate", "gender + exper", "gender + rank"), "coef" = c(con$coefficients[2],con_1$coefficients[2],con_2$coefficients[2],con_3$coefficients[2],con_4$coefficients[2],con_5$coefficients[2],con_6$coefficients[2]))

con_tab_95 %>% mutate(
  diff = abs((coef[1]-coef)/coef[1]),
  confounder = ifelse(diff>=0.1, "Y", "N")
)



```


# 95 salary
```{r}

mul.fit <- lm(log_sal95 ~ .,lawsuit_log_95)
summary(mul.fit)

# let gender be a stratified factor
mul.fit_all_gender <- lm(log_sal95 ~ . + 
              gender*rank + gender*clin + gender*cert +
              gender*prate + gender*rank + gender*dept
              ,lawsuit_log_95)
summary(mul.fit_all_gender)


# only gender*rank is significant
mul.fit_fixed_gender <- lm(log_sal95 ~ . + gender*rank, lawsuit_log_95)
summary(mul.fit_fixed_gender)

# ANONA test model with all interaction terms and model with only gender*rank 
anova(mul.fit_fixed_gender,mul.fit_all_gender)
# Choose small model


# remove non-significant variable: prate
# test model with and without prate
mul.fit_no_prate <- update(mul.fit_fixed_gender, . ~ . -prate)
summary(mul.fit_no_prate)

# ANOVA
# P>0.05
# choose small model wothout prate
anova(mul.fit_no_prate,mul.fit_fixed_gender)

# Final stratified model
mul.fit_no_prate <- update(mul.fit_fixed_gender, . ~ . -prate)
summary(mul.fit_no_prate)
```

# Stratified model by rank
```{r}
lawsuit_log_95_prof = 
lawsuit_log_95 %>% 
  filter(rank == "Full professor")

lawsuit_log_95_asso = 
lawsuit_log_95 %>% 
  filter(rank == "Associate")

lawsuit_log_95_assi = 
lawsuit_log_95 %>% 
  filter(rank == "Assistant")

model_prof = lm(formula = log_sal95 ~ dept + clin + cert + exper + gender, data = lawsuit_log_95_prof)

model_asso = lm(formula = log_sal95 ~ dept + clin + cert + exper + gender, data = lawsuit_log_95_asso)

model_assi = lm(formula = log_sal95 ~ dept + clin + cert + exper + gender, data = lawsuit_log_95_assi)

summary(model_prof)
summary(model_asso)
summary(model_assi)
```

# model diagnosis
# 95
```{r}
# prate has multicollinearity
vif(model_prof)
vif(model_asso)
vif(model_assi)

```

heteroscedasticity, normality
```{r}
# outlier: 51th,65th,4th
# influencial: 68th
par(mfrow=c(2,2))
plot(model_prof)

# outlier: 47th, 15th
par(mfrow=c(2,2))
plot(model_asso)

# outlier: 22th, 40th
# influencial point: 68th
par(mfrow=c(2,2))
plot(model_assi)
```










